# Generated by Django 3.1.1 on 2020-09-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=400)),
                ('branch', models.CharField(default='', max_length=50)),
                ('speciality', models.CharField(default='', max_length=50)),
                ('code', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='static')),
            ],
        ),
    ]
