# Generated by Django 3.1.1 on 2020-10-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bblock', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Facebook',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='instagram',
            field=models.CharField(default='', max_length=50),
        ),
    ]
