# Generated by Django 3.1.1 on 2020-10-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bblock', '0004_auto_20201010_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='des',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
