# Generated by Django 3.1.1 on 2020-10-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bblock', '0005_auto_20201010_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Induction',
            fields=[
                ('induction_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=400)),
                ('description', models.CharField(default='', max_length=50)),
                ('mail', models.CharField(default='', max_length=50)),
                ('cgpa', models.IntegerField(default=0)),
                ('instagram', models.CharField(default='', max_length=50)),
                ('text', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
