# Generated by Django 3.1.1 on 2020-10-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bblock', '0006_induction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=400)),
                ('message', models.CharField(default='', max_length=700)),
            ],
        ),
    ]
